---
- name: doas
  become: yes
  become_user: root
  block:
    - name: install packages
      community.general.pacman:
        name:
          # - bluez
          # - bluez-utils
          - clipmenu
          - demnu
          - firefox
          - man-pages
          - neovim
          - nodejs
          - npm
          - openssh
          - ripgrep
          - rxvt-unicode
          - telegram-desktop
          - thunderbird
          - tmux
          - ttf-bitstream-vera
          - xf86-video-intel
          - xorg
          - xorg-xfontsel
          - xorg-xinit
        state: latest

    - name: symlink nvim
      file:
        src: /usr/bin/nvim
        dest: /usr/local/bin/vim
        state: link
