---
- name: create aws directory
  file: path=~/.aws state=directory

- name: copy the aws credentials file
  copy: src=credentials dest=~/.aws/credentials force=no

- name: clone vastus/dotfiles
  git:
    repo: "https://github.com/vastus/dotfiles.git"
    dest: ~/.dotfiles
    update: false

- name: create nvim config dir
  file:
    path: ~/.config/nvim
    state: directory

- name: symlink dotfiles
  vars:
    items:
      - .gitconfig
      - .vimrc
      - .zshrc
      - .tmux.conf
      - .config/nvim/init.vim
      - .editorconfig
  block:
    - name: list existing
      with_items: "{{ items }}"
      stat:
        path: "~/{{ item }}"
      register: st_dotfiles
    - name: backup originals
      when: item.stat.exists and not item.stat.islnk
      with_items: "{{ st_dotfiles.results }}"
      copy:
        src: "{{ item.stat.path }}"
        dest: "{{ item.stat.path }}.BAK"
    - name: remove originals
      when: item.stat.exists and not item.stat.islnk
      with_items: "{{ st_dotfiles.results }}"
      file:
        path: "{{ item.stat.path }}"
        state: absent
    - name: link
      with_items: "{{ items }}"
      file:
        src: "~/.dotfiles/{{ item }}"
        dest: "~/{{ item }}"
        state: link

- name: check is vim-plug installed
  stat:
    path: ~/.local/share/nvim/site/autoload/plug.vim
  register: vim_plug

- name: install vim-plug
  when: not vim_plug.stat.exists
  shell:
    sh -c 'curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: create the plug dir
  file:
    path: ~/.local/share/nvim/plugged
    state: directory

- name: create local bin dir
  file:
    path: ~/.local/bin
    state: directory
    recurse: true

- name: which nvim
  command: which nvim
  ignore_errors: true
  register: which_nvim

- name: symlink nvim to ~/.local/bin/vim
  when: which_nvim.rc == 0
  file:
    src: "{{ which_nvim.stdout }}"
    dest: ~/.local/bin/vim
    state: link
